spring:
    h2:
      console:
          enabled: true
          path: /h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:~/financeirodb
      username: sa
      password:
    jpa:
      hibernate:
          ddl-auto: update
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
      cache:
        connection:
          mode: CONNECTION
        channel:
          size: 50
          checkout-timeout: 10000
server:
    error:
      include-message: always
    port: 8083
client:
  viacepapi:
    uri: https://viacep.com.br/ws/
sendgrid:
  sendgrid-api-key: secret
application:
  email: brunaccelestino@gmail.com
springdoc:
  api-docs:
    path: /api-docs
business:
  financeiro:
      url: ${VARIAVEL_URL:http://localhost:9080/pagamento/fornecedor}
      message:
        queue:
          fornecedor: fornecedor
          ordem_compra: ordem_compra
          pagamento: pagamento_ordem_compra
          ordem_compra_pago: ordem_compra_pago