spring:
    h2:
      console:
          enabled: true
          path: /h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:~/financeirodb
      username: sa
      password:
    jpa:
      hibernate:
          ddl-auto: update
server:
    error:
      include-message: always
    port: 8083
client:
  viacepapi:
    uri: https://viacep.com.br/ws/
sendgrid:
  sendgrid-api-key: secret
application:
  email: brunaccelestino@gmail.com
springdoc:
  api-docs:
    path: /api-docs